---
title: "Cohesión barrial en perspectiva territorial"
author: "Cristóbal Ortiz"
date: '2022-11-08'
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    theme: paper
    highlight: pygments
    toc_float:
      collapsed: yes
    code_folding: show
  word_document:
    toc: yes
header-includes:
   - \usepackage{floatrow}
   - \floatsetup[figure]{capposition=top}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "left",
	fig.topcaption = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE
)
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}

library(poLCA)
library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
library(spatstat)
library(gtools)
library(sf)
library(elsoc)
library(lubridate)
library(viridis)
library(treemapify)
library(statar)
```

```{r datos-elsoc, message=FALSE, warning=FALSE, include=FALSE}

load(url("https://dataverse.harvard.edu/api/access/datafile/6160173"))
load(url("https://dataverse.harvard.edu/api/access/datafile/6160174"))

# Datos territoriales ELSOC
elsoc::load_elsoc('territorial-2017')
territorial <- merge(elsoc_wide_2016_2021, elsoc_terr_2017, by="idencuesta")
```

# 1. Apego al barrio

## 1.1. Sentido de pertenencia al barrio

```{r spb-ola, fig.cap = 'Nivel de pertenencia al barrio según ola'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t02_01, t02_02, t02_03, t02_04)) %>% 
  mutate(spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>%
  as_label(ola) %>% 
  prop(x = spb_rec, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = spb_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 4)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos).\nNota 2: Pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "Este barrio es parte de mi" o "Me siento integrado/a en este barrio".')
```


```{r spb-ola-zona, fig.cap = 'Nivel de pertenencia al barrio según ola y zona'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t02_01, t02_02, t02_03, t02_04)) %>% 
  mutate(spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>% 
  prop(x = spb_rec, by = c(ola, zona1), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(spb_rec == 'De acuerdo o\ntotalmente de acuerdo') %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=2.868 (1.503 individuos).\nNota 2: Pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "Este barrio es parte de mi" o "Me siento integrado/a en este barrio".')
```

```{r spb-ola-estrato, fig.cap = 'Nivel de pertenencia al barrio según ola y tipo de ciudad'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t02_01, t02_02, t02_03, t02_04)) %>% 
  mutate(spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
         estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>% 
  prop(x = spb_rec, by = c(ola, estrato), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(spb_rec == 'De acuerdo o\ntotalmente de acuerdo') %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 2.5) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=2.868 (1.503 individuos).\nNota 2: Pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "Este barrio es parte de mi" o "Me siento integrado/a en este barrio".')

```

```{r spb-ola-quintil, fig.cap = 'Nivel de pertenencia al barrio según quintil de ingresos y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t02_01, t02_02, t02_03, t02_04),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(
  m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar,
  spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))
         ) %>%
  ungroup() %>% 
  prop(spb_rec, by = c(quintil, ola), na.rm = TRUE) %>% 
  filter(spb_rec == "De acuerdo o\ntotalmente de acuerdo") %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos).\nNota 2: Pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "Este barrio es parte de mi" o "Me siento integrado/a en este barrio".')
```


```{r spb-ola-quintil-zona, fig.cap = 'Nivel de pertenencia al barrio según ola, quintil y zona'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t02_01, t02_02, t02_03, t02_04),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(
  m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar,
  spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
  zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))
         ) %>%
  ungroup() %>% 
  prop(spb_rec, by = c(quintil, ola, zona1), na.rm = TRUE) %>% 
  filter(spb_rec == "De acuerdo o\ntotalmente de acuerdo") %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  facet_wrap(.~ zona1) +
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos).\nNota 2: La pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "Este barrio es parte de mi" o "Me siento integrado/a en este barrio".')
```

## 1.2. Arraigo al barrio

```{r arraigo-ola, fig.cap = 'Deseo de movilidad residencial según ola de estudio.'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !is_nsnr(t05)) %>%
  mutate(t05 = factor(t05, labels = c("Si, a otro barrio\nde la comuna", 
                                      "Si, a otra comuna", 
                                      "No, porque estoy\nbien donde estoy", 
                                      "No, no puedo\naunque quisiera"))) %>%
  as_label(ola, t05) %>%
  prop(x = t05, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = t05, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black', 'black'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos)')
```

```{r arraigo-ola-zona, fig.cap = 'Deseo de movilidad residencial según zona geográfica y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% 4:5 & !t05 %in% c(-888, -999)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  as_label(ola) %>%
  prop(t05 == 3, by = c(ola, zona1), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, title = NULL, 
     subtitle = 'Porcentaje que responde "No, porque estoy bien donde estoy"',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r arraigo-ola-estrato, fig.cap = 'Deseo de movilidad residencial según tipo de ciudad y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% 4:5 & !t05 %in% c(-888, -999)) %>% 
  mutate(estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  as_label(ola) %>%
  prop(t05 == 3, by = c(ola, estrato), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, title = NULL, 
     subtitle = 'Porcentaje que responde "No, porque estoy bien donde estoy"',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r arraigo-ola-quintil, fig.cap = 'Deseo de movilidad residencial según quintil de ingresos y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(t05),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))
         ) %>%
  ungroup() %>% 
  prop(t05 == 3 , by = c(quintil, ola), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "No, porque estoy bien donde estoy"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```

```{r arraigo-ola-quintil-zona, fig.cap = 'Deseo de movilidad residencial según quintil, ola y zona'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(t05),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}')),
         zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  ungroup() %>% 
  prop(t05 == 3 , by = c(quintil, ola, zona1), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  facet_wrap(.~ zona1) +
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "No, porque estoy bien donde estoy"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```

# 2. Relaciones vecinales

## 2.1. Sociabilidad barrial

```{r soci-ola, echo=FALSE, fig.cap = 'Nivel de sociabilidad barrial según ola'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t03_01, t03_02, t03_03, t03_04)) %>% 
  mutate(soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>%
  as_label(ola) %>% 
  prop(x = soci_rec, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = soci_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 4)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "La gente en este barrio es sociable" o "La gente en este barrio es colaboradora".')
```

```{r soci-ola-zona, fig.cap = 'Nivel de sociabilidad barrial según ola y zona'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t03_01, t03_02, t03_03, t03_04)) %>% 
  mutate(soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>% 
  prop(x = soci_rec, by = c(ola, zona1), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(soci_rec == 'De acuerdo o\ntotalmente de acuerdo') %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=2.868 (1.503 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "La gente en este barrio es sociable" o "La gente en este barrio es colaboradora".')
```

```{r soci-ola-estrato, fig.cap = 'Nivel de sociabilidad barrial según ola y tipo de ciudad'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t03_01, t03_02, t03_03, t03_04)) %>% 
  mutate(soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
         estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>% 
  prop(x = soci_rec, by = c(ola, estrato), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(soci_rec == 'De acuerdo o\ntotalmente de acuerdo') %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 2.5) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=2.868 (1.503 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "La gente en este barrio es sociable" o "La gente en este barrio es colaboradora".')

```

```{r soci-ola-quintil, fig.cap = 'Nivel de sociabilidad barrial según quintil de ingresos y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t03_01, t03_02, t03_03, t03_04),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(
  m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar,
  soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
  soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                    labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))
         ) %>%
  ungroup() %>% 
  prop(soci_rec, by = c(quintil, ola), na.rm = TRUE) %>% 
  filter(soci_rec == "De acuerdo o\ntotalmente de acuerdo") %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "La gente en este barrio es sociable" o "La gente en este barrio es colaboradora".')
```

```{r soci-ola-quintil-zona, fig.cap = 'Nivel de sociabilidad barrial según ola, quintil y zona'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:5, !is_nsnr(t03_01, t03_02, t03_03, t03_04),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(
  m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar,
  soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
  soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                    labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}')),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  ungroup() %>% 
  prop(soci_rec, by = c(quintil, ola, zona1), na.rm = TRUE) %>% 
  filter(soci_rec == "De acuerdo o\ntotalmente de acuerdo") %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  facet_wrap(.~ zona1) +
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con afirmaciones como "La gente en este barrio es sociable" o "La gente en este barrio es colaboradora".')
```

## 2.2. Confianza en vecinos

```{r vecinos-ola, fig.cap = 'Confianza en vecinos, según ola de estudio.'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !is_nsnr(t01)) %>% 
  mutate(barrio_conf = factor(car::recode(t01, "1:2 = 1; 3 = 2; 4:5 = 3"),
                               levels = 1:3,
                               labels = c('Muy poco o poco', 'Algo', 'Bastante o mucho'))) %>%
  sjlabelled::as_label(ola) %>%

  prop(x = barrio_conf, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = barrio_conf, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos)')

```

```{r vecinos-zona, fig.cap = 'Confianza en vecinos, según zona geográfica y ola del estudios'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !t01 %in% c(-888, -999)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana")))%>%
  sjlabelled::as_label(ola) %>%

  prop(x = t01 %in% 4:5, by = c(ola, zona1), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) + 
  labs(x = NULL, y = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "Bastante o mucho"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r vecinos-estrato, fig.cap = 'Confianza en vecinos según tipo de ciudad y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !t01 %in% c(-888, -999)) %>% 
  mutate(estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  sjlabelled::as_label(ola) %>%

  prop(x = t01 %in% 4:5, by = c(ola, estrato), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
  labs(x = NULL, y = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "Bastante o mucho"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r vecinos-quintil, fig.cap = 'Confianza en vecinos, según quintil de ingresos y ola del estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(t01),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))
         ) %>%
  ungroup() %>% 
  prop(t01 %in% 4:5, by = c(quintil, ola), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "Bastante o mucho"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```

```{r vecinos-ola-quintil-zona, fig.cap = 'Confianza en vecinos según ola, quintil y zona'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(t01),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}')),
         zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  ungroup() %>% 
  prop(t01 %in% 4:5, by = c(quintil, ola, zona1), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  facet_wrap(.~ zona1) +
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "Bastante o mucho"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```


## 2.3. Lazos fuertes

```{r lazos-ola, fig.cap = 'Grado permanencia de lazos fuertes en el barrio según ola'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:4, !is_nsnr(t04_05)) %>% 
  mutate(t04_05 = factor(car::recode(t04_05, "4:5 = 1; 3 = 2; 1:2 = 3"),
                         levels = 1:3,
                         labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>%
  as_label(ola) %>% 
  prop(x = t04_05, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = t04_05, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 4)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x  = NULL, y = NULL, title = NULL,
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.462 (1.513 individuos)')
```


```{r lazos-ola-zona, fig.cap = 'Grado permanencia de lazos fuertes  según ola y zona'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:4, !is_nsnr(t04_05)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>% 
  as_label(ola) %>% 
  prop(t04_05 %in% 1:2, by = c(ola, zona1), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = "Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=2.868 (1.503 individuos)")
```

```{r lazos-ola-estrato, fig.cap = 'Grado permanencia de lazos fuertes  según ola y tipo de ciudad'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:4, !is_nsnr(t04_05)) %>% 
  mutate(estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>% 
  as_label(ola) %>% 
  prop(t04_05 %in% 1:2, by = c(ola, estrato), na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 2) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = "Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=2.868 (1.503 individuos)")

```

```{r lazos-ola-quintil, fig.cap = 'Grado permanencia de lazos fuertes  según quintil de ingresos y ola del estudio'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:4, !is_nsnr(t04_05),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(
  m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))
         ) %>%
  ungroup() %>% 
  as_label(ola) %>% 
  prop(t04_05 %in% 1:2, by = c(quintil, ola), na.rm = TRUE) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```

```{r lazos-ola-quintil-zona, fig.cap = 'Grado permanencia de lazos fuertes  según quintil de ingresos y ola del estudio'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:4, !is_nsnr(t04_05),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(
  m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}')),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  ungroup() %>% 
  as_label(ola) %>% 
  prop(t04_05 %in% 1:2, by = c(quintil, ola, zona1), na.rm = TRUE) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01)+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  facet_wrap(.~ zona1) +
  labs(y = NULL, x = NULL, title = NULL, 
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```


# 3. Compromiso cívico local

## 3.1. Participación junta de vecinos

```{r membresia-ola, fig.cap = 'Membresía a junta de vecinos según ola de estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !is_nsnr(c12_01)) %>% 
  sjlabelled::as_label(c12_01, ola) %>%
  prop(x = c12_01, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = c12_01, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 2)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, title = NULL,
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos)')

```

```{r membresia-zona, fig.cap = 'Miembros activos a junta de vecinos según zona geográfica y ola del estudios'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !c12_01 %in% c(-888, -999)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana")))%>%
  as_label(c12_01, ola) %>%
  prop(x = c12_01, by = c(ola, zona1), na.rm = TRUE) %>%
  filter(c12_01 == "Miembro activo") %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, title = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r membresia-estrato, fig.cap = 'Miembros activos a junta de vecinos, según tipo de ciudad y ola del estudio'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !c12_01 %in% c(-888, -999)) %>% 
  mutate(estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  as_label(ola, c12_01) %>%
  prop(x = c12_01, by = c(ola, estrato), na.rm = TRUE) %>% 
  filter(c12_01 == "Miembro activo") %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0), legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, title = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r membresia-ola-quintil, fig.cap = 'Miembros activos a junta de vecinos según quintil y ola del estudio'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, !is_nsnr(c07_01),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))) %>%
  ungroup() %>% 
  as_label(ola, c12_01) %>%
  prop(x = c12_01, by = c(ola, quintil), na.rm = TRUE) %>% 
  filter(c12_01 == "Miembro activo") %>% 
  ggplot(aes(y = prop, x = quintil, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0), legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, title = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r membresia-ola-quintil-zona, fig.cap = 'Miembros activos a junta de vecinos, según ola, quintil y zona'}
elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1, !is_nsnr(c07_01),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))) %>%
  ungroup() %>% 
  as_label(ola, c12_01) %>%
  prop(x = c12_01, by = c(ola, quintil, zona1), na.rm = TRUE) %>% 
  filter(c12_01 == "Miembro activo") %>% 
  ggplot(aes(y = prop, x = quintil, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0), legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 2.5) +
  facet_wrap(.~ zona1) +
labs(x = NULL, y = NULL, title = NULL, 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

## 3.2. Apoyo social

```{r frecvisita-ola, fig.cap = 'Frecuencia de visita a vecinos según ola de estudio'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !c07_01 %in% c(-888, -999)) %>% 
  mutate(barrio_conf = factor(car::recode(c07_01, "1 = 1; 2 = 2; 3 = 3"),
                               levels = c(1,2,3),
                               labels = c('Nunca', 'Una o dos veces', 'Mas de dos veces'))) %>%
  sjlabelled::as_label(ola) %>%
  prop(x = barrio_conf, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = barrio_conf, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85, direction = 1) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.557 (1.513 individuos)')

```

```{r frecvisita-zona, fig.cap = 'Frecuencia de visita a vecinos según zona geográfica'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !c07_01 %in% c(-888, -999)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana")))%>%
  sjlabelled::as_label(ola) %>%

  prop(x = c07_01 %in% 2:3, by = c(ola, zona1), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) + 
  labs(x = NULL, y = NULL, title = NULL, 
       subtitle = 'Porcentaje que visitó una o más veces',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r frecvisita-estrato, fig.cap = 'Frecuencia de visita a vecinos según estrato'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% c(4,5) & !c07_01 %in% c(-888, -999)) %>% 
  mutate(estrato = factor(estrato, levels = c(1,2,3,4,5,6),
                          labels = c('Gran\nSantiago', 'Gran\nValparaíso', 'Gran\nConcepción',
                                     'Ciudades\ngrandes', 'Ciudades\nmedianas', 'Ciudades\npequeñas'))) %>%
  as_label(ola) %>%
  prop(x = c07_01 %in% 2:3, by = c(ola, estrato), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = estrato, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
  labs(x = NULL, y = NULL, title = NULL,
       subtitle = 'Porcentaje que visitó una o más veces',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r frecvisita-quintil, fig.cap = 'Frecuencia de visita a vecinos por ola y quintil'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(c07_01),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}'))) %>%
  ungroup() %>% 
  prop(c07_01 %in% 2:3, by = c(quintil, ola), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  labs(y = NULL, x = NULL, title = NULL,
       subtitle = 'Porcentaje que visitó una o más veces',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```

```{r frecvisita-ola-quintil-zona, fig.cap = 'Frecuencia de visita a vecinos por ola, quintil y zona'}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & !is_nsnr(c07_01),
         !is_nsnr(m30, m30b, nhogar1, m46_nhogar, m54)) %>% 
  mutate(m30 = as.numeric(car::recode(m30, "1 = 110000; 2 = 251000; 
  3 = 305000; 4 = 355000; 5 = 400000; 
  6 = 445000; 7 = 490000; 8 = 535000; 9 = 585000; 10 = 640000; 
  11 = 700000; 12 = 765000; 13 = 845000; 14 = 935000; 15 = 1040000;
  16 = 1180000; 17 = 1375000; 18 = 1670000; 19 = 2275000; 20 = 2700000; NA = NA")),
  m30b = as.numeric(car::recode(m30b, "1 = 170000; 2 = 300000; 3 = 400000; 4 = 600000; 5 = 1200000; NA = NA")),
  m29_imp = ifelse(!is_nsnr(m29), m29, ifelse(ola == 5, m30b, m30)),
  nhogar = case_when(ola == 1 ~ nhogar1,
                     ola == 2 ~ m46_nhogar,
                     TRUE ~ m54),
  ypc = m29_imp / nhogar) %>% 
  group_by(ola) %>% 
  mutate(quintil = xtile(ypc, n = 5, wt = ponderador02),
         quintil = factor(quintil, levels = 1:5, labels = glue::glue('Quintil {1:5}')),
         zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  ungroup() %>% 
  as_label(ola) %>% 
  prop(c07_01 %in% 2:3, by = c(quintil, ola, zona1), na.rm = TRUE) %>% 
  filter(quintil %in% c('Quintil 1', 'Quintil 5')) %>% 
  ggplot(aes(y = prop, x = ola, color = quintil, group = quintil,
             label = scales::percent(prop, .1))) +
  geom_point(size = 1.75) + 
  geom_line() +
  theme_bw() +   
  scale_color_viridis_d(begin = 0, end = .66, direction = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  geom_text_repel(size = 3, nudge_y = .01) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  facet_wrap(.~ zona1) +
  labs(y = NULL, x = NULL, title = NULL,
       subtitle = 'Porcentaje que visitó una o más veces',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.308 (1.513 individuos)')
```