---
title: "La Cohesión Barrial en Perspectiva Territorial"
author: "Cristóbal Ortiz - Asistente L4 COES"
date: '2022-11-16'
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: paper
    highlight: pygments
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
header-includes:
   - \usepackage{floatrow}
   - \floatsetup[figure]{capposition=top}
editor_options: 
  chunk_output_type: inline
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "left",
	fig.topcaption = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE
)
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}

library(poLCA)
library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
library(spatstat)
library(gtools)
library(sf)
library(elsoc)
library(lubridate)
library(viridis)
library(treemapify)
library(statar)
```

```{r datos-elsoc, message=FALSE, warning=FALSE, include=FALSE}

load(url("https://dataverse.harvard.edu/api/access/datafile/6160173"))
load(url("https://dataverse.harvard.edu/api/access/datafile/6160174"))
getwd()
load("../ELSOC_Long.RData")

# Datos territoriales ELSOC
elsoc::load_elsoc('territorial-2017')
territorial <- merge(elsoc_wide_2016_2021, elsoc_terr_2017, by="idencuesta")
```

# 1. Apego al barrio

## 1.1. Sentido de pertenencia al barrio

```{r spb-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !is_nsnr(t02_01, t02_02, t02_03, t02_04)) %>% 
  mutate(spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>%
  as_label(ola) %>% 
  prop(x = spb_rec, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = spb_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     title = 'Nivel de pertenencia al barrio según año',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas, N=1818.\nNota 2: La pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con las afirmaciones "Este es el barrio ideal para mi", "Me siento integrado/a en este barrio",\n"Me identifico con la gente de este barrio", "Este barrio es parte de mi".')
```


```{r spb-ola-zona}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !is_nsnr(t02_01, t02_02, t02_03, t02_04)) %>% 
  mutate(spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>% 
  as_label(ola, zona1) %>% 
  prop(x = spb_rec, by = c(ola, zona1), na.rm = TRUE) %>%
  filter(spb_rec == 'De acuerdo o\ntotalmente de acuerdo') %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 2) +
  labs(x = NULL, y = NULL,
       title = 'Nivel de pertenencia al barrio según año y macrozona',
       subtitle = "Porcentaje que responde 'de acuerdo o totalmente de acuerdo'",
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas, N=1818.\nNota 2: La pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con las afirmaciones "Este es el barrio ideal para mi", "Me siento integrado/a en este barrio",\n"Me identifico con la gente de este barrio", "Este barrio es parte de mi".')

```


```{r spb-ola-region}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !is_nsnr(t02_01, t02_02, t02_03, t02_04)) %>% 
  mutate(spb = (t02_01 + t02_02 + t02_03 + t02_04)/4,
         spb_rec = factor(cut(spb, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo",
                                             "Ni de acuerdo\nni en desacuerdo",
                                             "De acuerdo o\ntotalmente de acuerdo")),
  regiones = recode(region, 
                    "Aysen del general carlos ibanhez del campo" = "Aysen", 
                    "Aysén del general carlos ibáñez del campo" = "Aysen",
                    "Bio bio" = "Biobío", "Biobio" = "Biobío", 
                    "La araucania" = "La Araucanía", "Araucania" = "La Araucanía",  "La araucanía" = "La Araucanía",
                    "Libertador general bernardo o'higgins" = "Ohiggins", 
                    "Libertador general bernardo ohiggins" = "Ohiggins", 
                    "Los rios" = "Los Ríos", "Los ríos" = "Los Ríos",
                    "Metropolitana de santiago" = "Metropolitana", 
                    "Nhuble"= "Ñuble", "
                    Tarapaca" = "Tarapacá", 
                    "Valparaiso" = "Valparaíso",
                    "Los lagos" = "Los Lagos")) %>% 
  as_label(ola) %>% 
  prop(x = spb_rec, by = c(ola, regiones), na.rm = TRUE) %>%
  filter(spb_rec == 'De acuerdo o\ntotalmente de acuerdo', 
         regiones %in% c("Biobío","Los Ríos","La Araucanía", "Los Lagos")) %>% 
  ggplot(aes(y = prop, x = regiones, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 2) +
  labs(x = NULL, y = NULL,
       title = 'Nivel de pertenencia al barrio según año y región',
       subtitle = "Porcentaje que responde 'de acuerdo o totalmente de acuerdo'",
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas, N=1818.\nNota 2: La pertenencia al barrio corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con las afirmaciones "Este es el barrio ideal para mi", "Me siento integrado/a en este barrio",\n"Me identifico con la gente de este barrio", "Este barrio es parte de mi".')
```

## 1.2. Arraigo físico 

```{r arraigo-ola}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !is_nsnr(t05)) %>%
  mutate(t05 = factor(t05, labels = c("Si, a otro barrio\nde la comuna", 
                                      "Si, a otra comuna", 
                                      "No, porque estoy\nbien donde estoy", 
                                      "No, no puedo\naunque quisiera"))) %>%
  as_label(ola, t05) %>%
  prop(x = t05, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = t05, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black', 'black'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     title = 'Intención de movilidad residencial según ola de estudio',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos)')
```

```{r arraigo-ola-zona}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% 4:5 & !t05 %in% c(-888, -999)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>%
  as_label(ola) %>%
  prop(t05 == 3, by = c(ola, zona1), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, 
     title = 'Intención de movilidad residencial según zona geográfica y ola del estudio',
     subtitle = 'Porcentaje que responde "No, porque estoy bien donde estoy"',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r arraigo-ola-region}

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & ola %in% 1:6 & !t05 %in% c(-888, -999)) %>% 
  mutate(regiones = recode(region, 
                    "Aysen del general carlos ibanhez del campo" = "Aysen", 
                    "Aysén del general carlos ibáñez del campo" = "Aysen",
                    "Bio bio" = "Biobío", "Biobio" = "Biobío", 
                    "La araucania" = "La Araucanía", "Araucania" = "La Araucanía",  "La araucanía" = "La Araucanía",
                    "Libertador general bernardo o'higgins" = "Ohiggins", 
                    "Libertador general bernardo ohiggins" = "Ohiggins", 
                    "Los rios" = "Los Ríos", "Los ríos" = "Los Ríos", 
                    "Metropolitana de santiago" = "Metropolitana", 
                    "Nhuble"= "Ñuble", "
                    Tarapaca" = "Tarapacá", 
                    "Valparaiso" = "Valparaíso",
                    "Los lagos" = "Los Lagos")) %>% 
  as_label(ola) %>% 
  prop(t05 == 3, by = c(ola, regiones), na.rm = TRUE) %>% 
  filter(regiones %in% c("Biobío","Los Ríos","La Araucanía", "Los Lagos")) %>% 
  ggplot(aes(y = prop, x = regiones, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 2) +
labs(x = NULL, y = NULL, 
     title = 'Intención de movilidad residencial según tipo de ciudad y ola del estudio', 
     subtitle = 'Porcentaje que responde "No, porque estoy bien donde estoy"',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2021.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

# 2. Relaciones vecinales

## 2.1. Sociabilidad barrial

```{r soci-ola, echo=FALSE}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !is_nsnr(t03_01, t03_02, t03_03, t03_04)) %>% 
  mutate(soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo"))) %>%
  as_label(ola) %>% 
  prop(x = soci_rec, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = soci_rec, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     title = 'Nivel de sociabilidad barrial según año',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con las afirmaciones "En este barrio es facil hacer amigos", "La gente en este barrio es sociable",\n"La gente en este barrio es cordial", "La gente en este barrio es colaboradora".')
```

```{r soci-ola-zona}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !is_nsnr(t03_01, t03_02, t03_03, t03_04)) %>% 
  mutate(soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
         zona1 = factor(car::recode(region_cod, "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = c(1,2,3,4), 
                        labels = c("Norte","Centro","Sur","Metropolitana"))) %>% 
  prop(x = soci_rec, by = c(ola, zona1), na.rm = TRUE) %>% 
  as_label(ola) %>% 
  filter(soci_rec == 'De acuerdo o\ntotalmente de acuerdo') %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 2) +
  labs(x = NULL, y = NULL, 
       title = 'Nivel de sociabilidad barrial según año y zona',
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=1818 (1.503 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con las afirmaciones "En este barrio es facil hacer amigos", "La gente en este barrio es sociable",\n"La gente en este barrio es cordial", "La gente en este barrio es colaboradora".')
```

```{r soci-ola-region}
elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !is_nsnr(t03_01, t03_02, t03_03, t03_04)) %>% 
  mutate(soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         soci_rec = factor(cut(soci, breaks = c(0,2.75,3.75,5)),
                                  labels = c("Totalmente en desacuerdo o\nen desacuerdo","Ni de acuerdo\nni en desacuerdo","De acuerdo o\ntotalmente de acuerdo")),
  regiones = recode(region, 
                    "Aysen del general carlos ibanhez del campo" = "Aysen", 
                    "Aysén del general carlos ibáñez del campo" = "Aysen",
                    "Bio bio" = "Biobío", "Biobio" = "Biobío", 
                    "La araucania" = "La Araucanía", "Araucania" = "La Araucanía",  "La araucanía" = "La Araucanía",
                    "Libertador general bernardo o'higgins" = "Ohiggins", 
                    "Libertador general bernardo ohiggins" = "Ohiggins", 
                    "Los rios" = "Los Ríos", "Los ríos" = "Los Ríos", 
                    "Los lagos" = "Los Lagos",
                    "Metropolitana de santiago" = "Metropolitana", 
                    "Nhuble"= "Ñuble", "
                    Tarapaca" = "Tarapacá", 
                    "Valparaiso" = "Valparaíso")) %>% 
  as_label(ola) %>% 
  prop(x = soci_rec, by = c(ola, regiones), na.rm = TRUE) %>%
  filter(soci_rec == 'De acuerdo o\ntotalmente de acuerdo', 
         regiones %in% c("Biobío","Los Ríos","La Araucanía", "Los Lagos")) %>% 
  ggplot(aes(y = prop, x = regiones, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.5,
            position = position_dodge(width = .9),
            size = 2) +
  labs(x = NULL, y = NULL, 
       title = 'Nivel de sociabilidad barrial según año y región',
       subtitle = 'Porcentaje que responde "De acuerdo o totalmente de acuerdo"',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=1818 (1.503 individuos).\nNota 2: La sociabilidad barrial corresponde a un índice compuesto de cuatro ítems donde se consulta el grado\nde acuerdo con las afirmaciones "En este barrio es facil hacer amigos", "La gente en este barrio es sociable",\n"La gente en este barrio es cordial", "La gente en este barrio es colaboradora".')

```

# 3. Compromiso cívico local

## 3.1. Participación junta de vecinos

```{r membresia-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !is_nsnr(c12_01)) %>% 
  sjlabelled::as_label(c12_01, ola) %>%
  prop(x = c12_01, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = c12_01, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(end = .85) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, color = rep(c('white', 'white', 'black'), 3)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
labs(x = NULL, y = NULL, 
     title = 'Membresía a junta de vecinos según año de estudio',
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.529 (1.513 individuos)')

```

```{r membresia-zona}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & !c12_01 %in% c(-888, -999)) %>% 
  mutate(zona1 = factor(car::recode(region_cod, 
                                    "c(1,2,3,4,15)=1; c(5,6,7,8,16)=2; c(9,10,11,12,14)=3; 13=4"),
                        levels = 1:4,
                        labels = c("Norte","Centro","Sur","Metropolitana")))%>%
  as_label(c12_01, ola) %>%
  prop(x = c12_01, by = c(ola, zona1), na.rm = TRUE) %>%
  filter(c12_01 == "Miembro activo") %>% 
  ggplot(aes(y = prop, x = zona1, fill = ola, 
             label = scales::percent(prop, accuracy = .1))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .33, end = .66, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),           legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
labs(x = NULL, y = NULL, 
     title = 'Miembros activos a junta de vecinos según zona geográfica y ola del estudios', 
     caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```

```{r membresia-region}
elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 & ola %in% 1:6, !c12_01 %in% c(-888, -999)) %>% 
  mutate(regiones = recode(region, 
                    "Aysen del general carlos ibanhez del campo" = "Aysen", 
                    "Aysén del general carlos ibáñez del campo" = "Aysen",
                    "Bio bio" = "Biobío", "Biobio" = "Biobío", 
                    "La araucania" = "La Araucanía", "Araucania" = "La Araucanía",  "La araucanía" = "La Araucanía",
                    "Libertador general bernardo o'higgins" = "Ohiggins", 
                    "Libertador general bernardo ohiggins" = "Ohiggins", 
                    "Los rios" = "Los Ríos", "Los ríos" = "Los Ríos",
                    "Los lagos" = "Los Lagos",
                    "Metropolitana de santiago" = "Metropolitana", 
                    "Nhuble"= "Ñuble", "
                    Tarapaca" = "Tarapacá", 
                    "Valparaiso" = "Valparaíso")) %>% 
  as_label(ola, c12_01) %>%
  prop(x = c12_01, by = c(ola, regiones), na.rm = TRUE) %>% 
  filter(c12_01 == "Miembro activo")  %>%
  filter(regiones %in% c("Biobío","Los Ríos","La Araucanía", "Los Lagos")) %>% 
  ggplot(aes(y = prop, x = regiones, fill = ola, 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'dodge2') +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  scale_fill_viridis_d(begin = .22, end = .88, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  geom_text(vjust = -0.8,
            position = position_dodge(width = .9),
            size = 3) +
  labs(x = NULL, y = NULL, 
        title = 'Miembros activos a junta de vecinos, según región y ola',
       caption = 'Fuente: Elaboración propia en base a datos ELSOC 2016-2022.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=3.011 (1.513 individuos)')

```






